Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/home/ubuntu/miniconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
project_name/
|
|- data/
|   |- raw/
|   |   |- raw_data_file_1.csv
|   |   |- raw_data_file_2.csv
|   |   ...
|   |
|   |- processed/
|   |   |- processed_data_file_1.csv
|   |   |- processed_data_file_2.csv
|   |   ...
|
|- models/
|   |- model_1.pkl
|   |- model_2.pkl
|   ...
|
|- notebooks/
|   |- data_exploration.ipynb
|   |- model_training.ipynb
|   |- model_evaluation.ipynb
|   ...
|
|- src/
|   |- data/
|   |   |- data_processing.py
|   |   |- data_cleaning.py
|   |   ...
|   |
|   |- features/
|   |   |- feature_extraction.py
|   |   |- feature_selection.py
|   |   ...
|   |
|   |- models/
|   |   |- model_training.py
|   |   |- model_evaluation.py
|   |   ...
|   |
|   |- visualization/
|   |   |- visualizations.py
|   |   ...
|   |
|   |- utils/
|   |   |- utils.py
|   |   ...
|
|   |- tests/
|   |   |- test_data.py
|   |   |- test_features.py
|   |   |- test_visualization.py
|   |   |- test_models.py
|   |   |- test_utils.py
|   |   ...
|
|-- reports/
|   |-- figures/
|   |-- presentations/
|   |-- papers/
|
|- .gitignore
|- requirements.txt
|- README.md
------------------


[0;36m  Cell [0;32mIn[1], line 1[0;36m[0m
[0;31m    project_name/[0m
[0m                 ^[0m
[0;31mSyntaxError[0m[0;31m:[0m invalid syntax


